# CMake generated Testfile for 
# Source directory: E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/TESTING
# Build directory: E:/Program Files/Work/created by me/QT/lapackBinaries/BLAS/TESTING
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(BLAS-xblat1s "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat1s.exe" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat2s "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat2s.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/sblat2.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat3s "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat3s.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/sblat3.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat1d "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat1d.exe" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat2d "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat2d.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/dblat2.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat3d "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat3d.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/dblat3.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat1c "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat1c.exe" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat2c "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat2c.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/cblat2.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat3c "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat3c.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/cblat3.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat1z "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat1z.exe" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat2z "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat2z.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/zblat2.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
ADD_TEST(BLAS-xblat3z "C:/Program Files (x86)/CMake 2.8/bin/cmake.exe" "-DTEST=E:/Program Files/Work/created by me/QT/lapackBinaries/bin/xblat3z.exe" "-DINPUT=E:/Program Files/Work/created by me/QT/lapack-3.4.2/BLAS/zblat3.in" "-DINTDIR=." "-P" "E:/Program Files/Work/created by me/QT/lapack-3.4.2/TESTING/runtest.cmake")
